# Generated by Django 5.1.4 on 2025-01-15 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_alter_project_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('task_status', models.CharField(max_length=126)),
                ('task_date', models.DateField()),
                ('Project', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='base.project')),
            ],
        ),
    ]
