# Generated by Django 5.1.4 on 2025-01-15 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_tasks'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Tasks',
            new_name='Task',
        ),
    ]
