# Generated by Django 5.1.4 on 2025-01-15 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_rename_tasks_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Advance Tax', [('1', 'Data Collection'), ('2', 'Data Recieved'), ('3', 'Data Process / Working'), ('4', 'Approval From Sir'), ('5', 'Approval From Client'), ('6', 'Challan Sent'), ('7', 'Challan Paid')]), ('GSTR1', [('1', 'Follow Up'), ('2', 'Data Recieved'), ('3', 'Working / Process'), ('4', 'Query Sent To Client'), ('5', 'Answer Recieved From Client'), ('6', 'Checking By HOD'), ('7', 'Uploading')])], max_length=126),
        ),
    ]
