# Generated by Django 5.1.4 on 2025-01-15 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_alter_task_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='task_status',
            field=models.CharField(choices=[('Advance Tax', [('Data Collection', 'Data Collection'), ('Data Recieved', 'Data Recieved'), ('Data Process / Working', 'Data Process / Working'), ('Approval From Sir', 'Approval From Sir'), ('Approval From Client', 'Approval From Client'), ('Challan Sent', 'Challan Sent'), ('Challan Paid', 'Challan Paid')]), ('GSTR1', [('Follow Up', 'Follow Up'), ('Data Recieved', 'Data Recieved'), ('Working / Process', 'Working / Process'), ('Query Sent To Client', 'Query Sent To Client'), ('Answer Recieved From Client', 'Answer Recieved From Client'), ('Checking By HOD', 'Checking By HOD'), ('Uploading', 'Uploading')])], max_length=126),
        ),
    ]
