# Generated by Django 5.1.4 on 2025-01-17 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0017_alter_project_project_completed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='status',
        ),
    ]
